"""Braid-class census of jammed unique groups (2+1): the LQG / Bilson-Thompson test.

Unique groups are clusters of worldlines that touch each other at least once
while touching no other group (README "Unique Path Group"; engine `--subpaths`).
In 2+1 a group of n strands traces a genuine element of the braid group B_n:
two spatial axes plus conformal time is exactly the setting where braiding of
point strands is topologically meaningful. (In 3+1 point-strand braids are
always trivial -- strands slide past each other through the third dimension --
which is why Bilson-Thompson's preon model braids framed *ribbons*, not points.
So this census is 2+1-only by topology, not by tooling.)

Question: does packing pressure alone make touching groups *braid*, and if so
which B_3 classes appear? Bilson-Thompson's helon model (hep-ph/0503213;
hep-th/0603022 Sec. VI) builds ALL first-generation Standard Model fermions
from a single minimal 2-crossing 3-strand braiding template -- sigma1*sigma2^-1
(left-handed) or its mirror sigma2^-1*sigma1 (right-handed) -- with charge and
color carried entirely by ribbon twists that unframed point strands cannot
express. The unframed content of the whole first generation is therefore that
one chiral template (the "neutrino framework"), which is exactly what this
census can look for: does jamming produce sigma_i*sigma_j^-1 groups, and with
what left/right balance?

Method:
  * Reconstruct each strand's comoving trajectory X(z) = x(z)/sin z on the
    engine's z-grid interval [pi/(T+1), T*pi/(T+1)], supersampled, in the
    universal cover R^2 (each strand's formula IS its canonical lift; the
    torus only matters for contact detection, not for lifting).
  * Crossings = sign changes of DeltaX between two strands, bisected to the
    crossing time z*; the generator exponent is the sign of DeltaY(z*)
    (y is the projection depth -- fixed chirality convention).
  * The braid word is the z-ordered sequence of adjacent transpositions of the
    x-order. Missed tangential double-crossings contribute sigma*sigma^-1 =
    identity, so the *class* is robust to finite sampling even where the raw
    word is not.
  * 3-strand words are classified by the Burau representation at t = -1,
    sigma1 -> [[1,1],[0,1]], sigma2 -> [[1,0],[-1,1]] (into SL(2,Z)); the
    matrix together with the exponent sum is a COMPLETE invariant of B_3
    (the kernel of B_3 -> SL(2,Z) is generated by the full twist
    (sigma1*sigma2)^6, which the exponent sum detects). Names come from a
    shortest-word dictionary enumerated up to length --dict-len.
  * A crossing with |DeltaY(z*)| < 2/T (the engine's contact half-width) is
    "fragile": over-vs-under is below the packing's own resolution, so groups
    containing one are censused separately.

Usage::

    uv run python -m analysis.analyze_braids \
        --dumps 'data/converge/dumps/d2_*_sub_*.csv' --out figures/braids.png
"""

from __future__ import annotations

import argparse
import csv
import glob
import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from math import pi
from pathlib import Path

import numpy as np

_NAME_RE = re.compile(r"_T(?P<t>\d+)_s(?P<seed>\d+)")

# ---------------------------------------------------------------------------
# worldline evaluation
# ---------------------------------------------------------------------------


@dataclass
class Strand:
    """One worldline: per-axis wiggle terms + the sin(z) comoving offset."""

    ax: np.ndarray  # wiggle amplitudes, x axis
    bx: np.ndarray  # integer wiggle frequencies, x axis
    fx: np.ndarray  # wiggle phases, x axis
    ay: np.ndarray
    by: np.ndarray
    fy: np.ndarray
    ax2: float  # sin(1*z) amplitude (free comoving coordinate), x axis
    ay2: float
    gid: int

    def xy(self, z: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """Comoving position X = x/sin z, Y = y/sin z in the universal cover.

        Mirrors the engine: each wiggle term is re-pinned to zero at the
        endpoints by its own a*sin(f) offset.
        """
        sinz = np.sin(z)
        zz = z[:, None]
        x = np.sum(self.ax * (np.sin(self.bx * zz + self.fx) - np.sin(self.fx)), axis=1)
        y = np.sum(self.ay * (np.sin(self.by * zz + self.fy) - np.sin(self.fy)), axis=1)
        return (x + self.ax2 * sinz) / sinz, (y + self.ay2 * sinz) / sinz


def load_dump(path: str) -> list[Strand]:
    """Read a dump CSV (legacy single-wiggle or multi-term header) with gid."""
    with open(path) as fh:
        rows = [r for r in csv.DictReader(fh) if r.get("gid") not in (None, "")]
    if not rows:
        raise ValueError(f"{path}: no gid column -- need a --subpaths dump")
    multi = "ax_1" in rows[0]
    strands = []
    for r in rows:
        if multi:
            n = 1
            while f"ax_{n + 1}" in r and r[f"ax_{n + 1}"] not in (None, ""):
                n += 1
            keys = [str(j) for j in range(1, n + 1)]

            def get(pfx: str, r: dict = r, keys: list[str] = keys) -> np.ndarray:
                return np.array([float(r[f"{pfx}_{j}"]) for j in keys])
        else:

            def get(pfx: str, r: dict = r, keys: list[str] = []) -> np.ndarray:
                return np.array([float(r[pfx])])

        strands.append(
            Strand(
                get("ax"),
                get("bx"),
                get("fx"),
                get("ay"),
                get("by"),
                get("fy"),
                float(r["ax2"]),
                float(r["ay2"]),
                int(r["gid"]),
            )
        )
    return strands


# ---------------------------------------------------------------------------
# crossing extraction
# ---------------------------------------------------------------------------


@dataclass
class Crossing:
    z: float
    i: int  # strand index within the group (dump order)
    j: int
    dy_sign: int  # sign of Y_i - Y_j at the crossing (chirality raw material)
    fragile: bool  # |DeltaY| at the crossing below the contact scale 2/T


def pair_crossings(
    sa: Strand,
    sb: Strand,
    zgrid: np.ndarray,
    contact: float,
    xya: tuple[np.ndarray, np.ndarray] | None = None,
    xyb: tuple[np.ndarray, np.ndarray] | None = None,
) -> list[Crossing]:
    """All x-projection crossings of two strands, bisected to the crossing z.

    xya/xyb are optional precomputed trajectories on zgrid (a per-group cache);
    the bisection always re-evaluates the exact formulas at refined z values.
    """
    xa, _ = xya if xya is not None else sa.xy(zgrid)
    xb, _ = xyb if xyb is not None else sb.xy(zgrid)
    dx = xa - xb
    flips = np.nonzero(np.sign(dx[:-1]) * np.sign(dx[1:]) < 0)[0]
    if len(flips) == 0:
        return []
    lo, hi = zgrid[flips].copy(), zgrid[flips + 1].copy()
    slo = np.sign(dx[flips])
    for _ in range(50):
        mid = 0.5 * (lo + hi)
        xma, _ = sa.xy(mid)
        xmb, _ = sb.xy(mid)
        smid = np.sign(xma - xmb)
        left = smid == slo
        lo = np.where(left, mid, lo)
        hi = np.where(left, hi, mid)
    zstar = 0.5 * (lo + hi)
    _, ysa = sa.xy(zstar)
    _, ysb = sb.xy(zstar)
    dy = ysa - ysb
    out = []
    for k in range(len(zstar)):
        s = 1 if dy[k] > 0 else -1
        out.append(Crossing(float(zstar[k]), 0, 1, s, bool(abs(dy[k]) < contact)))
    return out


def crossing_exponent(c: Crossing, ki: int, kj: int) -> int:
    """Generator exponent for a crossing of strands i (position ki) and j (kj).

    The exponent is the y-sign of the strand on the LEFT just before the
    crossing (y is the projection depth): a rotating pair then accumulates
    same-sign crossings, as it must -- a fixed-label DeltaY sign would
    alternate on every other crossing of the same handedness.
    """
    return c.dy_sign if ki < kj else -c.dy_sign


@dataclass
class GroupBraid:
    n: int
    word: list[tuple[int, int]]  # (generator position k in 1..n-1, exponent)
    exp_sum: int
    perm: tuple[int, ...]  # final permutation of the initial x-order
    pair_sums: dict[tuple[int, int], int]  # signed crossing count per pair
    fragile: int  # crossings below the contact scale
    anomalies: int  # non-adjacent events (order rebuilt from positions)


def group_braid(strands: list[Strand], zgrid: np.ndarray, contact: float) -> GroupBraid:
    """Assemble the group's braid word from all pairwise crossing events."""
    n = len(strands)
    cache = [s.xy(zgrid) for s in strands]
    events: list[Crossing] = []
    for i in range(n):
        for j in range(i + 1, n):
            for c in pair_crossings(
                strands[i], strands[j], zgrid, contact, cache[i], cache[j]
            ):
                c.i, c.j = i, j
                events.append(c)
    events.sort(key=lambda c: c.z)

    x0 = np.array([s.xy(zgrid[:1])[0][0] for s in strands])
    order = list(np.argsort(x0))  # strand indices, left to right
    word: list[tuple[int, int]] = []
    pair_sums: dict[tuple[int, int], int] = defaultdict(int)
    anomalies = 0
    for c in events:
        ki, kj = order.index(c.i), order.index(c.j)
        if abs(ki - kj) != 1:
            # A missed intermediate event de-synced the ordering; rebuild it
            # from actual positions just before this crossing.
            anomalies += 1
            zq = np.array([c.z - 1e-9])
            xs = np.array([s.xy(zq)[0][0] for s in strands])
            order = list(np.argsort(xs))
            ki, kj = order.index(c.i), order.index(c.j)
            if abs(ki - kj) != 1:
                continue  # still inconsistent -- drop the event, keep counting
        k = min(ki, kj) + 1  # generator index, 1-based
        s = crossing_exponent(c, ki, kj)
        word.append((k, s))
        pair_sums[(min(c.i, c.j), max(c.i, c.j))] += s
        order[min(ki, kj)], order[max(ki, kj)] = order[max(ki, kj)], order[min(ki, kj)]
    perm = tuple(order)
    return GroupBraid(
        n=n,
        word=word,
        exp_sum=sum(s for _, s in word),
        perm=perm,
        pair_sums=dict(pair_sums),
        fragile=sum(1 for c in events if c.fragile),
        anomalies=anomalies,
    )


# ---------------------------------------------------------------------------
# B_3 classification: Burau at t = -1 (matrix + exponent sum is complete)
# ---------------------------------------------------------------------------

_S1 = np.array([[1, 1], [0, 1]], dtype=object)
_S2 = np.array([[1, 0], [-1, 1]], dtype=object)
_S1I = np.array([[1, -1], [0, 1]], dtype=object)
_S2I = np.array([[1, 0], [1, 1]], dtype=object)
_GEN = {(1, 1): _S1, (2, 1): _S2, (1, -1): _S1I, (2, -1): _S2I}


def b3_invariant(word: list[tuple[int, int]]) -> tuple[tuple[int, ...], int]:
    """(flattened SL(2,Z) matrix, exponent sum) -- a complete B_3 invariant."""
    m = np.eye(2, dtype=object)
    for k, s in word:
        m = m @ _GEN[(k, s)]
    return tuple(int(v) for v in m.ravel()), sum(s for _, s in word)


def build_b3_dictionary(maxlen: int) -> dict[tuple, list[tuple[int, int]]]:
    """Shortest word (BFS by length) for every B_3 class reachable by maxlen."""
    dictionary: dict[tuple, list[tuple[int, int]]] = {}
    frontier: list[list[tuple[int, int]]] = [[]]
    dictionary[b3_invariant([])] = []
    for _ in range(maxlen):
        nxt = []
        for w in frontier:
            for g in ((1, 1), (1, -1), (2, 1), (2, -1)):
                w2 = w + [g]
                key = b3_invariant(w2)
                if key not in dictionary:
                    dictionary[key] = w2
                    nxt.append(w2)
        frontier = nxt
    return dictionary


def word_str(word: list[tuple[int, int]]) -> str:
    if not word:
        return "1 (trivial)"
    return ".".join(f"s{k}" + ("'" if s < 0 else "") for k, s in word)


# ---------------------------------------------------------------------------
# census
# ---------------------------------------------------------------------------


@dataclass
class DumpResult:
    t: int
    seed: int
    size_hist: Counter = field(default_factory=Counter)
    groups: list[dict] = field(default_factory=list)
    skipped_giant: int = 0


def analyze_dump(
    path: str, supersample: int, max_group: int, b3dict: dict
) -> DumpResult:
    m = _NAME_RE.search(Path(path).name)
    if not m:
        raise ValueError(f"cannot parse T/seed from {path}")
    t, seed = int(m["t"]), int(m["seed"])
    strands = load_dump(path)
    by_gid: dict[int, list[Strand]] = defaultdict(list)
    for s in strands:
        by_gid[s.gid].append(s)

    # Engine z-grid [pi/(T+1), T*pi/(T+1)], supersampled for crossing capture.
    zgrid = np.linspace(pi / (t + 1), t * pi / (t + 1), (t - 1) * supersample + 1)
    contact = 2.0 / t

    res = DumpResult(t=t, seed=seed)
    for gid, members in by_gid.items():
        res.size_hist[len(members)] += 1
        if len(members) < 2:
            continue
        if len(members) > max_group:
            res.skipped_giant += 1
            continue
        gb = group_braid(members, zgrid, contact)
        row = {
            "t": t,
            "seed": seed,
            "gid": gid,
            "n": gb.n,
            "n_crossings": len(gb.word),
            "exp_sum": gb.exp_sum,
            "perm": "".join(map(str, gb.perm)),
            "fragile": gb.fragile,
            "anomalies": gb.anomalies,
            "class": "",
            "class_key": "",
            "class_len": "",
        }
        if gb.n == 3:
            key = b3_invariant(gb.word)
            short = b3dict.get(key)
            row["class_key"] = str(key)
            if short is not None:
                row["class"] = word_str(short)
                row["class_len"] = len(short)
            else:
                # Too deep for the dictionary: bucket the display label by
                # exponent sum (the exact invariant stays in class_key).
                row["class"] = f"deep (e={gb.exp_sum:+d})"
                row["class_len"] = -1
        elif gb.n == 2:
            e = gb.exp_sum
            if e == 0:
                row["class"] = "1 (trivial)"
            elif abs(e) == 1:
                row["class"] = "s1" if e > 0 else "s1'"
            else:
                row["class"] = f"s1^{e}"
            row["class_key"] = str(e)
            row["class_len"] = abs(e)
        res.groups.append(row)
    return res


def group_is_braided(g: dict) -> bool:
    """Nontrivial-braid test: exact for n<=3, exp-sum lower bound for n>=4."""
    if g["class"]:
        return g["class"] != "1 (trivial)"
    return g["exp_sum"] != 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dumps",
        default="data/converge/dumps/d2_*_sub_*.csv",
        help="glob of 2+1 subpath dumps (need a gid column)",
    )
    parser.add_argument("--out", type=Path, default=Path("figures/braids.png"))
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("figures/braids_groups.csv"),
        help="per-group classification table",
    )
    parser.add_argument(
        "--supersample",
        type=int,
        default=8,
        help="z samples per engine step for crossing capture",
    )
    parser.add_argument(
        "--max-group",
        type=int,
        default=48,
        help="skip braid extraction above this group size",
    )
    parser.add_argument(
        "--dict-len", type=int, default=6, help="B_3 shortest-word dictionary depth"
    )
    args = parser.parse_args()

    paths = sorted(glob.glob(args.dumps))
    if not paths:
        raise SystemExit(f"no dumps match {args.dumps}")
    b3dict = build_b3_dictionary(args.dict_len)
    print(f"B_3 dictionary: {len(b3dict)} classes up to word length {args.dict_len}")

    results = [analyze_dump(p, args.supersample, args.max_group, b3dict) for p in paths]
    for r, p in zip(results, paths):
        n_groups = sum(1 for _ in r.groups)
        print(
            f"  {Path(p).name}: {n_groups} multi-strand groups analyzed"
            + (f" ({r.skipped_giant} giant skipped)" if r.skipped_giant else "")
        )

    rows = [g for r in results for g in r.groups]
    skipped = sum(r.skipped_giant for r in results)
    if skipped:
        print(
            f"NOTE: {skipped} groups larger than --max-group={args.max_group} "
            "were skipped for braid extraction (still in the size census)."
        )

    if not rows:
        raise SystemExit("no multi-strand groups found in the given dumps")
    args.csv.parent.mkdir(parents=True, exist_ok=True)
    with open(args.csv, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {args.csv} ({len(rows)} groups)")

    # ---- printed census ----
    pairs = [g for g in rows if g["n"] == 2]
    triples = [g for g in rows if g["n"] == 3]
    braided_pairs = [g for g in pairs if g["exp_sum"] != 0]
    solid_triples = [g for g in triples if g["fragile"] == 0]
    print(f"\n=== census over {len(paths)} dumps ===")
    print(
        f"pairs (n=2): {len(pairs)}, with nonzero linking: {len(braided_pairs)} "
        f"({100 * len(braided_pairs) / max(len(pairs), 1):.1f}%)"
    )
    print(f"triples (n=3): {len(triples)}, fragile-free: {len(solid_triples)}")
    for label, subset in (("all triples", triples), ("fragile-free", solid_triples)):
        census = Counter(g["class"] for g in subset)
        print(f"\n  B_3 classes ({label}):")
        for cls, cnt in census.most_common(15):
            print(f"    {cls:<24} {cnt:>5}  ({100 * cnt / max(len(subset), 1):.1f}%)")

    # Chirality balance: does jamming prefer a handedness? (parity test)
    pe_pos = sum(1 for g in pairs if g["exp_sum"] > 0)
    pe_neg = sum(1 for g in pairs if g["exp_sum"] < 0)
    te_pos = sum(1 for g in triples if g["exp_sum"] > 0)
    te_neg = sum(1 for g in triples if g["exp_sum"] < 0)
    print(
        f"\n  chirality balance (exp_sum sign): pairs +{pe_pos}/-{pe_neg}, "
        f"triples +{te_pos}/-{te_neg}"
    )

    nontrivial = Counter()
    total_by_n = Counter()
    for g in rows:
        total_by_n[g["n"]] += 1
        if group_is_braided(g):
            nontrivial[g["n"]] += 1
    print("\n  braided fraction by group size (n>=4: exp-sum lower bound):")
    for n in sorted(total_by_n):
        if n > 12:
            break
        print(
            f"    n={n}: {nontrivial[n]}/{total_by_n[n]} "
            f"({100 * nontrivial[n] / total_by_n[n]:.0f}%)"
        )

    frag = sum(g["fragile"] for g in rows)
    total_x = sum(g["n_crossings"] for g in rows)
    anom = sum(g["anomalies"] for g in rows)
    print(
        f"\n  crossings: {total_x} total, {frag} fragile "
        f"({100 * frag / max(total_x, 1):.1f}%), {anom} order anomalies"
    )

    make_figure(results, rows, args.out)


def make_figure(results: list[DumpResult], rows: list[dict], out: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 4, figsize=(21, 5))

    # (a) group-size distribution by T (sequential colormap: T is ordered)
    ax = axes[0]
    by_t: dict[int, Counter] = defaultdict(Counter)
    for r in results:
        by_t[r.t].update(r.size_hist)
    ts = sorted(by_t)
    cmap = plt.colormaps["viridis"]
    for idx, t in enumerate(ts):
        sizes = sorted(by_t[t])
        counts = [by_t[t][s] for s in sizes]
        ax.loglog(
            sizes,
            counts,
            "o-",
            ms=3,
            lw=1,
            color=cmap(idx / max(len(ts) - 1, 1)),
            label=f"T={t}",
        )
    ax.set_xlabel("group size n (strands)")
    ax.set_ylabel("groups (all seeds)")
    ax.set_title("(a) unique-group size distribution")
    ax.legend(fontsize=7)
    ax.grid(True, which="both", alpha=0.25)

    # (b) pair (n=2) linking: exponent-sum distribution
    ax = axes[1]
    es = [g["exp_sum"] for g in rows if g["n"] == 2]
    lo, hi = min(es, default=-1), max(es, default=1)
    bins = np.arange(lo - 0.5, hi + 1.5)
    ax.hist(es, bins=bins, color="tab:blue", edgecolor="white")
    ax.set_xlabel("signed crossing sum e (B$_2$ class)")
    ax.set_ylabel("pairs")
    ax.set_title("(b) 2-strand groups: linking census")
    ax.grid(True, axis="y", alpha=0.25)

    # (c) 3-strand class census, Bilson-Thompson template highlighted
    ax = axes[2]
    solid = [g for g in rows if g["n"] == 3 and g["fragile"] == 0]
    census = Counter(g["class"] for g in solid)
    top = census.most_common(12)
    labels = [c for c, _ in top]
    counts = [v for _, v in top]
    bt_like = {"s1.s2'", "s2.s1'", "s1'.s2", "s2'.s1"}  # sigma_i sigma_j^-1 templates
    colors = ["tab:orange" if lb in bt_like else "tab:blue" for lb in labels]
    ax.barh(range(len(top))[::-1], counts, color=colors, edgecolor="white")
    ax.set_yticks(range(len(top))[::-1])
    ax.set_yticklabels(labels, fontsize=8, family="monospace")
    ax.set_xlabel("groups (fragile-free)")
    ax.set_title(
        "(c) B$_3$ classes of 3-strand groups\n"
        "(orange = Bilson-Thompson $\\sigma_i\\sigma_j^{-1}$ template)"
    )
    ax.grid(True, axis="x", alpha=0.25)

    # (d) braided fraction vs group size
    ax = axes[3]
    total_by_n = Counter()
    braided_by_n = Counter()
    for g in rows:
        total_by_n[g["n"]] += 1
        if group_is_braided(g):
            braided_by_n[g["n"]] += 1
    ns = [n for n in sorted(total_by_n) if total_by_n[n] >= 5]
    frac = [braided_by_n[n] / total_by_n[n] for n in ns]
    ax.plot(ns, frac, "o-", color="tab:blue")
    ax.set_xlabel("group size n")
    ax.set_ylabel("fraction with nontrivial braid")
    ax.set_ylim(0, 1.05)
    ax.set_title("(d) does touching imply braiding?")
    ax.grid(True, alpha=0.25)

    fig.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=130)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
